title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: Nighthawk Coders
github_username: abbymanalo
baseurl: "/abbym"
remote_theme: pages-themes/merlot@v0.2.0
# remote_theme: pages-themes/merlot@v0.2.0
# remote_theme: pages-themes/merlot@v0.2.0
# remote_theme: pages-themes/merlot@v0.2.0
# remote_theme: pages-themes/merlot@v0.2.0
# remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
future: true
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
